[package]
name = "mau-run"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = { version = "0.4.3", features = ["serde"] }
libloading = "0.8.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
